name: Check version bump
on:
  pull_request:
    branches: ['main']

jobs:
  check-version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if package.json version has changed
        run: |
          VERSION_CHANGED=$(git diff origin/main...HEAD package.json | grep -E '^\+.*"version"' -c)
          if [ "$VERSION_CHANGED" -lt 1 ]; then 
            echo "Remember to bump the version in package.json"
            exit 1
          fi
